### ISSUE TITLE
Variable player count

### ISSUE THREAD

**Issue by Tajmoti** [chalankolachtanovity/Bot_ready#6]
The bot should be able to count to a different number of players other than 5, for example when starting a Wingman match or when some player currently isn't able to play.

Explore options on how to implement this in a backwards-compatible manner. For example, there could be a possibility for the first player to add an extra parameter which would be the desired player count like this: `!ready 2`. If it's missing, default to the current value of 5. Or maybe add a separate command for starting the countdown like `!startready 2`.

**Comment by chalankolachtanovity** [comment]
Done

**Comment by chalankolachtanovity** [comment]
Added in #13
